### ISSUE TITLE
jar files

### ISSUE THREAD

**Issue by karmstro77** [Esri/twitter-for-geoevent#3]
Are the 10.3 jar files hosted here? I cant seem to find them. I see http-transport jar. Shouldnt there also be an adapter jar file?

**Comment by jgravois** [comment]
hi @karmstro77.  i don't work on this project, but im 99% sure you're supposed to use Maven to compile the source yourself, (as described in the repositorie's README.

**Comment by rsunderman** [comment]
@karmstro77 - We are working to update the product gallery [link](http://www.arcgis.com/home/item.html?id=041138094e5348eb902f4b71175eeb6f) to provide a download bundle which includes a pre-built 10.3 Twitter adapter and transport. The bundle will include an updated tutorial. For now, you can build the source offering yourself from the GitHub repo - the available source is for the 10.3 product release.

**Comment by droberge2015** [comment]
any chance somebody would compile the adaptor for 10.5 (.jar) and put it in the repository? Or update the file from the product gallery to reflect 10.5? Thanks!`

**Comment by hanoch** [comment]
we are going to update the gallery with the 10.5 release soon

**Comment by droberge2015** [comment]
ok thanks! Should the 10.4 version work then? because when I set it up, I get 0 records coming in....

**Comment by eironside** [comment]
The .jar files are hosted here along with documentation for installing/using: https://www.arcgis.com/home/item.html?id=cf5509c1f3d94364b264be0518423a5b
