### ISSUE TITLE
Twitter inbound connector's transport logs an HTTP "unexpected error" -- input stream terminates

### ISSUE THREAD

**Issue by rsunderman** [Esri/twitter-for-geoevent#5]
###### Description:
When created and started, *Receive Tweets* inbound connector (*twitter-in*) will receive Tweets for a period of time and then stop. The input is still running, but its event count on the GeoEvent Manager's Monitor page is not incrementing. The *Time Since Last* metric on the Monitor page will allow you to subtract however many *hh:mm:ss* from "now" in order to locate the following errors in the karaf.log:
```
... com.esri.ges.framework.transport.http-transport - 10.3.0
Cannot read the HTTP response. An unexpected error has occurred while reading the The HTTP response.
Error: SSL peer shut down incorrectly.
```

###### Workaround:
User can stop and restart the GEx input. They should then see that the event count for their *twitter-in* input will once again begin to increment.

**Comment by cris6097** [comment]
Using GeoEvent daily build 10.3.1.4941, I created Twitter input and let it run for ~17 hours and I did not come across error message "SSL peer shut down incorrectly". Also, Monitor page was still incrementing.
